### ISSUE TITLE
KSP Type: BCGSL fails on single process runs

### ISSUE THREAD

**Issue by ahmadia** [erdc-cm/proteus#112]
This actually looks like it could be an internal bug in PETSc to me.

```
Traceback (most recent call last):
  File "/home/aron/proteus/linux2/bin/parun", line 439, in <module>
    runName + '_run_prof')
  File "/home/aron/proteus/linux2/lib/python2.7/site-packages/proteus/Profiling.py", line 174, in __call__
    return func(*func_args, **func_kwargs)
  File "/home/aron/proteus/linux2/lib/python2.7/site-packages/proteus/NumericalSolution.py", line 702, in calculateSolution
    par_rList=model.par_rList)
  File "/home/aron/proteus/linux2/lib/python2.7/site-packages/proteus/NonlinearSolvers.py", line 1850, in solveMultilevel
    par_r = par_r)
  File "/home/aron/proteus/linux2/lib/python2.7/site-packages/proteus/NonlinearSolvers.py", line 801, in solve
    self.linearSolver.solve(u=self.du,b=r,par_u=self.par_du,par_b=par_r)
  File "/home/aron/proteus/linux2/lib/python2.7/site-packages/proteus/LinearSolvers.py", line 533, in solve
    self.ksp.solve(par_b,par_u)
  File "KSP.pyx", line 342, in petsc4py.PETSc.KSP.solve (src/petsc4py.PETSc.c:113846)
petsc4py.PETSc.Error: error code 62
[0] KSPSolve() line 441 in /home/aron/sandbox/acoe/hdb/tmp/petsc-dg2gkmdbrhc7/src/ksp/ksp/interface/itfunc.c
[0] KSPSolve_BCGSL() line 278 in /home/aron/sandbox/acoe/hdb/tmp/petsc-dg2gkmdbrhc7/src/ksp/ksp/impls/bcgsl/bcgsl.c
[0] VecMAXPY() line 1257 in /home/aron/sandbox/acoe/hdb/tmp/petsc-dg2gkmdbrhc7/src/vec/vec/interface/rvector.c
[0] Invalid argument
[0] Scalar value must be same on all processes, argument # 3
```

**Comment by cekees** [comment]
I've not seen this error in recent work using bcgsl.  Will reopen if it comes up again.
