### ISSUE TITLE
hdf5 crashes on multiple runs

### ISSUE THREAD

**Issue by robertsawko** [erdc-cm/proteus#203]
I am running a running a sort of Monte Carlo. I generate different initial conditions for the Burgers' equation and then solve the equation with Burgers. This is all done via

```python
for i in range(N):
    so.name = pList[0].name = "mc_run{0:05d}".format(i)
    xi = np.pi / 10 * randn()
    eta = randn()
    pList[0].coefficients = pList[0].ForcedBurgersEqn(
        nu=1e-6,
        rofx=lambda x, t: forcing_term(x, t, eta),
        sigma=1
    )
    pList[0].initialConditions = {0: sineIC(xi)}

    ns = NumericalSolution.NS_base(so, pList, nList, so.sList, opts)
    ns.calculateSolution(so.name)
    del ns
```

I was hoping to get 50000 of these simulations but unfortunately it breaks at a random point with the following error:

```
Traceback (most recent call last):
  File "burgers_mc_run.py", line 44, in <module>
    ns.calculateSolution(so.name)
  File "/home/c111269/projects/proteus/linux2/lib/python2.7/site-packages/proteus/NumericalSolution.py", line 811, in calculateSolution
    self.archiveSolution(model,index,self.systemStepController.t_system_last)
  File "/home/c111269/projects/proteus/linux2/lib/python2.7/site-packages/proteus/NumericalSolution.py", line 932, in archiveSolution
    writeVelocityPostProcessor=self.opts.writeVPP)
  File "/home/c111269/projects/proteus/linux2/lib/python2.7/site-packages/proteus/Transport.py", line 5283, in archiveFiniteElementSolutions
    t,init=False,meshChanged=meshChanged,tCount=tCount)
  File "/home/c111269/projects/proteus/linux2/lib/python2.7/site-packages/proteus/FemTools.py", line 5170, in writeMeshXdmf
    tCount=tCount)
  File "/home/c111269/projects/proteus/linux2/lib/python2.7/site-packages/proteus/Archiver.py", line 508, in writeMeshXdmf_DGP2Lagrange
    mesh.writeMeshXdmf(ar,"Spatial_Domain",t,init,meshChanged,tCount=tCount)
  File "/home/c111269/projects/proteus/linux2/lib/python2.7/site-packages/proteus/MeshTools.py", line 4872, in writeMeshXdmf
    Mesh.writeMeshXdmf(self,ar,name,t,init,meshChanged,"Polyline",tCount)
  File "/home/c111269/projects/proteus/linux2/lib/python2.7/site-packages/proteus/MeshTools.py", line 738, in writeMeshXdmf
    ar.hdfFile.createArray("/",'nodeMapL2G'+name+`tCount`,self.globalMesh.nodeNumbering_subdomain2global)
  File "/home/c111269/projects/proteus/linux2/lib/python2.7/site-packages/tables/file.py", line 780, in createArray
    object=object, title=title, byteorder=byteorder)
  File "/home/c111269/projects/proteus/linux2/lib/python2.7/site-packages/tables/array.py", line 167, in __init__
    byteorder, _log)
  File "/home/c111269/projects/proteus/linux2/lib/python2.7/site-packages/tables/leaf.py", line 263, in __init__
    super(Leaf, self).__init__(parentNode, name, _log)
  File "/home/c111269/projects/proteus/linux2/lib/python2.7/site-packages/tables/node.py", line 259, in __init__
    self._g_postInitHook()
  File "/home/c111269/projects/proteus/linux2/lib/python2.7/site-packages/tables/leaf.py", line 313, in _g_postInitHook
    self._v_attrs._g__setattr('FLAVOR', self._flavor)
  File "/home/c111269/projects/proteus/linux2/lib/python2.7/site-packages/tables/attributeset.py", line 386, in _g__setattr
    self._g_setAttr(self._v_node, name, stvalue)
  File "hdf5Extension.pyx", line 429, in tables.hdf5Extension.AttributeSet._g_setAttr (tables/hdf5Extension.c:4064)
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5A.c", line 929, in H5Awrite
    not an attribute

End of HDF5 error back trace

Can't set attribute 'FLAVOR' in node:
 /nodeMapL2GSpatial_Domain114 (Array(101,)) ''.
Closing remaining open files: mc_run006720.h5... done
```

At first I thought it's something to do with keeping the archives close, but it clearly isn't related. RAM is not increasing and there's a lot of disk space available. I feel it may be related to the random variable that I generate, although I would expect the simulation to crash in that case. This is the last 50 lines of proteus.log.
```
[    3956] Explicit RK dcoefs= [ 1.   0.5  1. ] substeps = [0.63056711754306027, 0.62753483383783437, 0.63056711754306027] 
[    3956] Explicit RK t= 0.630567117543 tLast=0.630567117543 self.tLast= 0.624502550133 
[    3956] Explicit RK dcoefs= [ 1.   0.5  1. ] substeps = [0.63056711754306027, 0.62753483383783437, 0.63056711754306027] 
[    3956] Explicit RK t= 0.630567117543 tLast=0.630567117543 self.tLast= 0.624502550133 
[    3956] SplitOperator_Min choose_dt_system t_system_last= 0.624502550133 dt_system= 0.00606456741045 t_system= 0.630567117543 
[    3956] Step Taken, System time step t= 6.30567e-01, dt= 6.06457e-03
[    3956] Explicit RK dcoefs= [ 1.   0.5  1. ] substeps = [0.63056711754306027, 0.62753483383783437, 0.63056711754306027] 
[    3956] Explicit RK t= 0.630567117543 tLast=0.630567117543 self.tLast= 0.624502550133 
[    3956] Step Taken, Model step t= 6.30567e-01, dt= 6.06457e-03 for model mc_run00672
[    3956] Writing mesh header for  model = mc_run00672 at time t=0.624502550133
[    3956] Writing solution for  model = mc_run00672
[    3956] System time step t= 6.30567e-01, dt= 6.06457e-03
[    3956] Split operator iteration 0
[    3956] Model: mc_run00672
[    3956] Fractional step  6.30567e-01 for model mc_run00672
[    3956] Step exact called for model mc_run00672
[    3956] Explicit RK dcoefs= [ 1.   0.5  1. ] substeps = [0.63056711754306027, 0.62753483383783437, 0.63056711754306027] 
[    3956] Explicit RK t= 0.630567117543 tLast=0.630567117543 self.tLast= 0.624502550133 
[    3956] Model step t= 6.30567e-01, dt= 6.06457e-03 for model mc_run00672
[    3956] Model substep t= 6.30567e-01 for model mc_run00672
[    3956] Model substep t= 6.30567e-01 for model mc_run00672 model.timeIntegration.t=  6.30567e-01
[    3956] ExplicitRK calcElemenCoefsNoDt lstage= 0 nStages= 3
[    3956] SSPRKNewton it 1 norm(r) 0.002128861986957671
[    3956] ExplicitRK calcElemenCoefsNoDt lstage= 0 nStages= 3
[    3956] ExplicitRK calcElemenCoefsNoDt lstage= 0 nStages= 3
[    3956] Model substep t= 6.27535e-01 for model mc_run00672
[    3956] Model substep t= 6.27535e-01 for model mc_run00672 model.timeIntegration.t=  6.27535e-01
[    3956] ExplicitRK calcElemenCoefsNoDt lstage= 1 nStages= 3
[    3956] SSPRKNewton it 1 norm(r) 0.0010519929609342361
[    3956] ExplicitRK calcElemenCoefsNoDt lstage= 1 nStages= 3
[    3956] ExplicitRK calcElemenCoefsNoDt lstage= 1 nStages= 3
[    3956] Model substep t= 6.30567e-01 for model mc_run00672
[    3956] Model substep t= 6.30567e-01 for model mc_run00672 model.timeIntegration.t=  6.30567e-01
[    3956] ExplicitRK calcElemenCoefsNoDt lstage= 2 nStages= 3
[    3956] SSPRKNewton it 1 norm(r) 0.0010633169655707296
[    3956] ExplicitRK calcElemenCoefsNoDt lstage= 2 nStages= 3
[    3956] ExplicitRK calcElemenCoefsNoDt lstage= 2 nStages= 3
[    3956] SO_base modelStepTaken for model= mc_run00672 t_system_last= 0.624502550133 t_model_last= 0.624502550133  setting to t_stepSequence= 0.630567117543 
[    3956] Step Taken, t_stepSequence= 0.630567117543 Model step t= 6.30567e-01, dt= 6.06457e-03 for model mc_run00672
[    3956] Explicit RK dcoefs= [ 1.   0.5  1. ] substeps = [0.63660748229333053, 0.6335872999181954, 0.63660748229333053] 
[    3956] Explicit RK t= 0.636607482293 tLast=0.636607482293 self.tLast= 0.630567117543 
[    3956] Explicit RK dcoefs= [ 1.   0.5  1. ] substeps = [0.63660748229333053, 0.6335872999181954, 0.63660748229333053] 
[    3956] Explicit RK t= 0.636607482293 tLast=0.636607482293 self.tLast= 0.630567117543 
[    3956] SplitOperator_Min choose_dt_system t_system_last= 0.630567117543 dt_system= 0.00604036475027 t_system= 0.636607482293 
[    3956] Step Taken, System time step t= 6.36607e-01, dt= 6.04036e-03
[    3956] Explicit RK dcoefs= [ 1.   0.5  1. ] substeps = [0.63660748229333053, 0.6335872999181954, 0.63660748229333053] 
[    3956] Explicit RK t= 0.636607482293 tLast=0.636607482293 self.tLast= 0.630567117543 
[    3956] Step Taken, Model step t= 6.36607e-01, dt= 6.04036e-03 for model mc_run00672
[    3956] Writing mesh header for  model = mc_run00672 at time t=0.630567117543
[    3956] Writing solution for  model = mc_run00672
```

I am currently investigating the effect of random variables - will try to run the same with fixed values, but I just wanted to check with you that there's nothing seriously wrong about the saving or running the code in the way I present above.

By the way, I should really take advantage of the parallelisation in the above code.

**Comment by cekees** [comment]
I don't recall seeing that before. ns.calculateSolution() closes the hdf5 archive and the xml file right before it returns, so I don't think this is some interaction between the archives for each run (you've carefully made sure the names don't overlap anyway).  How many simulations did  it complete before it threw this error? You can also check the return value of calculationSolution to see if it is failing at some point, but that should still close down the archive properly.  It's not at all efficient or convenient to work  with, but you can also set `opts.useTextArchive=True` and it won't use HDF5. You get  one data directory per simulation with one ascii text  file for each array that would be stored in the hdf5.

**Comment by AlmostSurelyRob** [comment]
I've tried a couple of things by now. It seems to crash at a random point after doing 500-800 simulations. Yes, I figured out that the archives are closed before going to the next run. I also run the same simulation n times by just fixing xi and eta to zero and it crashed after around 800 so I also know it's nothing to do with the randomness itself.

I will try the option now.

**Comment by AlmostSurelyRob** [comment]
I confirmed that `useTextArchive=True` doesn't cause any issues. The MC just passed 4000 without a crash. The MC with hdf5 crashed every 500-800 cases with the same error about setting the FLAVOR.

**Comment by robertsawko** [comment]
It has now emerged that the computer I run it on had a faulty drive. It may have turned faulty whilst I was overdoing with verbosity of the debug messages, which accumulate very quickly with MC runs. After a few changes (and still on the same computer with a faulty drive) I don't seem to be getting these messages any more. Random behaviour is a sign of hardware failure to me. I will check it on some other machines and if that works I will close the issue.
